using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using YTS.Model.Attribute;
using YTS.Model.Table.Attribute;
using YTS.Tools;

namespace YTS.Model.Table
{
    /// <summary>
    /// 列信息模型
    /// </summary>
    public class ColumnInfo : AbsBasicDataModel
    {
        /// <summary>
        /// 解释翻译信息
        /// </summary>
        public string Name { get { return _Name; } set { _Name = value; } }
        private string _Name = string.Empty;

        /// <summary>
        /// 解释翻译信息
        /// </summary>
        public ExplainAttribute Explain { get { return _explain; } set { _explain = value; } }
        private ExplainAttribute _explain = null;

        /// <summary>
        /// 数据列特性
        /// </summary>
        public ColumnAttribute Attribute { get { return _attribute; } set { _attribute = value; } }
        private ColumnAttribute _attribute = null;

        /// <summary>
        /// 属性信息
        /// </summary>
        public PropertyInfo Property { get { return _property; } set { _property = value; } }
        private PropertyInfo _property = null;

        /// <summary>
        /// 排序比较 实现委托: Comparison泛型
        /// </summary>
        public static int SortMethod(ColumnInfo x, ColumnInfo y) {
            // 主键
            if (x.Attribute.IsPrimaryKey != y.Attribute.IsPrimaryKey) {
                return y.Attribute.IsPrimaryKey ? 1 : -1;
            }
            // 标识列
            if (x.Attribute.IsIDentity != y.Attribute.IsIDentity) {
                return y.Attribute.IsIDentity ? 1 : -1;
            }
            // 自动生成的值
            if (x.Attribute.IsAutoGenerated != y.Attribute.IsAutoGenerated) {
                return y.Attribute.IsAutoGenerated ? 1 : -1;
            }
            // 允许为空的值
            if (x.Attribute.IsCanBeNull != y.Attribute.IsCanBeNull) {
                return y.Attribute.IsCanBeNull ? 1 : -1;
            }
            // 排序序列
            int indexResult = Sort.Int(x.Attribute.SortIndex, y.Attribute.SortIndex);
            return indexResult == 0 ? Sort.String(x.Property.Name, y.Property.Name) : indexResult;
        }
    }
}
