using System;
using System.Collections.Generic;
using System.Reflection;
using YTS.Engine.ShineUpon;
using YTS.Tools;
using YTS.Tools.Model;

namespace YTS.Engine.DataBase
{
    /// <summary>
    /// 映射结果信息-数据表列
    /// </summary>
    /// <typeparam name="M">数据表映射模型</typeparam>
    public class ColumnModelParser<M> : ShineUponParser
        where M : AbsShineUpon
    {
        public ColumnModelParser() : base(typeof(M)) { }

        /// <summary>
        /// 获取信息列表
        /// </summary>
        public ColumnInfo[] GetList() {
            Dictionary<string, ColumnInfo> dic = this.GetDictionary<ColumnInfo>(info => {
                info.Attribute = ReflexHelp.AttributeFindOnly<ColumnAttribute>(info.Property);
                return CheckData.IsObjectNull(info.Attribute) ? null : info;
            });
            List<ColumnInfo> list = new List<ColumnInfo>(dic.Values);
            if (IsNeedSort()) {
                list.Sort(SortMethod);
            }
            return list.ToArray();
        }

        /// <summary>
        /// 获得列信息 可写
        /// </summary>
        public ColumnInfo[] GetListCanWrite() {
            ColumnInfo[] arr = GetList();
            return ConvertTool.ListConvertType(arr, info => {
                if (info.Attribute.IsAutoGenerated) {
                    return null;
                }
                return info;
            }, null);
        }

        /// <summary>
        /// 钩子: 判断是否需要排序
        /// </summary>
        /// <returns>是否需要布尔值</returns>
        public bool IsNeedSort() {
            return true;
        }

        /// <summary>
        /// 排序比较 实现委托: Comparison泛型
        /// </summary>
        public static int SortMethod(ColumnInfo x, ColumnInfo y) {
            // 主键
            if (x.Attribute.IsPrimaryKey != y.Attribute.IsPrimaryKey) {
                return y.Attribute.IsPrimaryKey ? 1 : -1;
            }
            // 标识列
            if (x.Attribute.IsIDentity != y.Attribute.IsIDentity) {
                return y.Attribute.IsIDentity ? 1 : -1;
            }
            // 自动生成的值
            if (x.Attribute.IsAutoGenerated != y.Attribute.IsAutoGenerated) {
                return y.Attribute.IsAutoGenerated ? 1 : -1;
            }
            // 允许为空的值
            if (x.Attribute.IsCanBeNull != y.Attribute.IsCanBeNull) {
                return y.Attribute.IsCanBeNull ? 1 : -1;
            }
            // 排序序列
            int indexResult = Sort.Int(x.Attribute.SortIndex, y.Attribute.SortIndex);
            return indexResult == 0 ? Sort.String(x.Property.Name, y.Property.Name) : indexResult;
        }
    }
}
